[2023-10-15 14:05:10,574: INFO: main:welcome to our custom log]
[2023-10-15 14:20:39,399: INFO: main:welcome to our custom log]
[2023-10-20 19:48:12,604: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-10-20 19:48:12,607: INFO: common:yaml file: params.yaml loaded successfully]
[2023-10-20 19:48:12,609: INFO: common:created directory at: artifacts]
[2023-10-20 19:48:12,611: INFO: common:created directory at: artifacts/data_ingestion]
[2023-10-20 19:48:12,613: INFO: 2624417567:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2023-10-20 19:53:10,766: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-10-20 19:53:10,770: INFO: common:yaml file: params.yaml loaded successfully]
[2023-10-20 19:53:10,771: INFO: common:created directory at: artifacts]
[2023-10-20 19:53:10,772: INFO: common:created directory at: artifacts/data_ingestion]
[2023-10-20 19:53:10,773: INFO: 84929902:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2023-10-20 19:53:23,552: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-10-20 19:53:23,555: INFO: common:yaml file: params.yaml loaded successfully]
[2023-10-20 19:53:23,556: INFO: common:created directory at: artifacts]
[2023-10-20 19:53:23,557: INFO: common:created directory at: artifacts/data_ingestion]
[2023-10-20 19:53:23,558: INFO: 84929902:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2023-10-20 19:53:59,133: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-10-20 19:53:59,136: INFO: common:yaml file: params.yaml loaded successfully]
[2023-10-20 19:53:59,138: INFO: common:created directory at: artifacts]
[2023-10-20 19:53:59,140: INFO: common:created directory at: artifacts/data_ingestion]
[2023-10-20 19:53:59,142: INFO: 4182046305:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2023-10-20 19:54:09,201: INFO: 4182046305:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-01-07 01:51:29,140: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-01-07 01:51:29,164: ERROR: main:'DataIngestionTrainingPipeline' object has no attribute 'main']
Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\main.py", line 14, in <module>
    data_ingestion.main()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'main'
[2024-01-07 01:54:27,611: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-01-07 01:54:27,626: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-01-07 01:54:27,626: INFO: common:yaml file: params.yaml loaded successfully]
[2024-01-07 01:54:27,626: INFO: common:created directory at: artifacts]
[2024-01-07 01:54:27,626: INFO: common:created directory at: artifacts/data_ingestion]
[2024-01-07 01:54:27,626: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-01-07 01:54:39,210: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-01-07 01:54:40,498: INFO: main:>>>>>> stage Data Ingestion stage completed successfully <<<<<

x=======x]
[2024-01-07 01:58:48,196: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-01-07 01:58:48,196: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-01-07 01:58:48,196: INFO: common:yaml file: params.yaml loaded successfully]
[2024-01-07 01:58:48,243: INFO: common:created directory at: artifacts]
[2024-01-07 01:58:48,243: INFO: common:created directory at: artifacts/data_ingestion]
[2024-01-07 01:58:48,249: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-01-07 01:58:59,462: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-01-07 01:59:00,321: INFO: main:>>>>>> stage Data Ingestion stage completed successfully <<<<<

x=======x]
 [2024-03-05 00:27:36,071: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:27:36,378: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:27:36,381: INFO: common:created directory at: artifacts]
[2024-03-05 00:30:29,957: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:30:29,961: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:30:29,963: INFO: common:created directory at: artifacts]
[2024-03-05 00:30:29,965: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:32:10,334: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:32:10,341: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:32:10,342: INFO: common:created directory at: artifacts]
[2024-03-05 00:32:10,343: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:35:23,592: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:35:23,594: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:35:23,595: INFO: common:created directory at: artifacts]
[2024-03-05 00:35:23,596: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:39:22,063: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:39:22,065: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:39:22,067: INFO: common:created directory at: artifacts]
[2024-03-05 00:39:22,067: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:39:49,159: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:39:49,161: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:39:49,162: INFO: common:created directory at: artifacts]
[2024-03-05 00:39:49,164: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:40:02,006: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-05 00:40:54,652: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:40:54,654: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:40:54,655: INFO: common:created directory at: artifacts]
[2024-03-05 00:40:54,657: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:40:55,068: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-05 00:41:15,044: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:41:15,047: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:41:15,049: INFO: common:created directory at: artifacts]
[2024-03-05 00:41:15,050: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:41:15,556: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-05 00:43:58,950: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:43:58,952: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:43:58,953: INFO: common:created directory at: artifacts]
[2024-03-05 00:43:58,988: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:43:59,367: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-05 00:44:06,651: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:44:06,654: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:44:06,655: INFO: common:created directory at: artifacts]
[2024-03-05 00:44:06,656: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:44:07,104: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-05 00:47:17,080: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 00:47:17,083: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 00:47:17,083: INFO: common:created directory at: artifacts]
[2024-03-05 00:47:17,084: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 00:47:17,522: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-05 11:41:51,352: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-05 11:41:51,379: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 11:41:51,388: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 11:41:51,389: INFO: common:created directory at: artifacts]
[2024-03-05 11:41:51,389: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-05 11:41:51,390: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-05 11:41:53,631: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-05 11:41:53,633: ERROR: main:[Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\main.py", line 15, in <module>
    data_ingestion.main()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 20, in main
    data_ingestion.extract_zip_file()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 41, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\zipfile.py", line 1286, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-03-05 12:03:29,139: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-05 12:03:29,140: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 12:03:29,141: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 12:03:29,142: INFO: common:created directory at: artifacts]
[2024-03-05 12:03:29,142: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-05 12:03:29,143: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-05 12:03:31,052: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-05 12:03:31,053: ERROR: main:[Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\main.py", line 15, in <module>
    data_ingestion.main()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 20, in main
    data_ingestion.extract_zip_file()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 41, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\zipfile.py", line 1286, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-03-05 12:16:23,191: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-05 12:16:23,192: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 12:16:23,194: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 12:16:23,194: INFO: common:created directory at: artifacts]
[2024-03-05 12:16:23,195: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-05 12:16:23,195: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-05 12:16:34,308: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-05 12:16:35,267: INFO: main:>>>>>> stage Data Ingestion stage completed successfully <<<<<

x=======x]
[2024-03-05 12:16:35,269: INFO: main:************]
[2024-03-05 12:16:35,269: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2024-03-05 12:16:35,270: ERROR: main:name 'CongigurationManager' is not defined]
Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\main.py", line 30, in <module>
    obj.main()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 20, in main
    raise e
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 14, in main
    config = CongigurationManager()
             ^^^^^^^^^^^^^^^^^^^^
NameError: name 'CongigurationManager' is not defined
[2024-03-05 12:19:35,943: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-05 12:19:35,945: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 12:19:35,946: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 12:19:35,947: INFO: common:created directory at: artifacts]
[2024-03-05 12:19:35,947: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-05 12:19:35,948: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-05 12:19:45,486: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-05 12:19:46,278: INFO: main:>>>>>> stage Data Ingestion stage completed successfully <<<<<

x=======x]
[2024-03-05 12:19:46,280: INFO: main:************]
[2024-03-05 12:19:46,280: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2024-03-05 12:19:46,285: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 12:19:46,289: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 12:19:46,291: INFO: common:created directory at: artifacts]
[2024-03-05 12:19:46,292: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-05 12:19:49,401: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-05 12:19:50,625: INFO: main:>>>>> stage Prepare base model completed <<<<<< 

 x==========x]
[2024-03-05 23:51:01,608: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 23:51:01,961: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 23:51:01,964: INFO: common:created directory at: artifacts]
[2024-03-05 23:51:01,967: INFO: common:created directory at: artifacts\training]
[2024-03-05 23:54:20,367: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-05 23:54:20,370: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-05 23:54:20,372: INFO: common:created directory at: artifacts]
[2024-03-05 23:54:20,373: INFO: common:created directory at: artifacts\training]
[2024-03-06 00:19:09,418: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 00:19:09,421: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 00:19:09,422: INFO: common:created directory at: artifacts]
[2024-03-06 00:19:09,423: INFO: common:created directory at: artifacts\training]
[2024-03-06 00:37:52,705: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 00:37:52,707: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 00:37:52,708: INFO: common:created directory at: artifacts]
[2024-03-06 00:37:52,710: INFO: common:created directory at: artifacts\training]
[2024-03-06 00:47:13,410: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 00:47:13,419: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 00:47:13,421: INFO: common:created directory at: artifacts]
[2024-03-06 00:47:13,423: INFO: common:created directory at: artifacts\training]
[2024-03-06 01:37:43,493: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 01:37:43,496: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 01:37:43,498: INFO: common:created directory at: artifacts]
[2024-03-06 01:37:43,500: INFO: common:created directory at: artifacts\training]
[2024-03-06 11:02:08,187: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-06 11:02:08,209: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 11:02:08,211: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 11:02:08,211: INFO: common:created directory at: artifacts]
[2024-03-06 11:02:08,212: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-06 11:02:08,213: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 11:02:20,571: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 11:02:21,823: INFO: main:>>>>>> stage Data Ingestion stage completed successfully <<<<<

x=======x]
[2024-03-06 11:02:21,824: INFO: main:************]
[2024-03-06 11:02:21,825: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2024-03-06 11:02:21,826: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 11:02:21,829: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 11:02:21,829: INFO: common:created directory at: artifacts]
[2024-03-06 11:02:21,830: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-06 11:02:25,819: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-06 11:02:27,382: INFO: main:>>>>> stage Prepare base model completed <<<<<< 

 x==========x]
[2024-03-06 11:02:27,386: INFO: main:*****************]
[2024-03-06 11:02:27,387: INFO: main:>>>>> stage Training started <<<<<<<]
[2024-03-06 11:02:27,395: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 11:02:27,402: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 11:02:27,405: INFO: common:created directory at: artifacts]
[2024-03-06 11:02:27,406: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-06 11:02:27,781: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-06 11:02:29,476: INFO: main:>>>>>> stage Training completed <<<<<<

 x=========x]
[2024-03-06 12:53:57,363: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-06 12:53:57,407: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 12:53:57,408: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 12:53:57,409: INFO: common:created directory at: artifacts]
[2024-03-06 12:53:57,410: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-06 12:53:57,410: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 12:54:09,562: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 12:54:10,465: INFO: main:>>>>>> stage Data Ingestion stage completed successfully <<<<<

x=======x]
[2024-03-06 12:54:10,466: INFO: main:************]
[2024-03-06 12:54:10,466: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2024-03-06 12:54:10,468: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 12:54:10,469: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 12:54:10,470: INFO: common:created directory at: artifacts]
[2024-03-06 12:54:10,470: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-06 12:54:13,519: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-06 12:54:15,415: INFO: main:>>>>> stage Prepare base model completed <<<<<< 

 x==========x]
[2024-03-06 12:54:15,418: INFO: main:*****************]
[2024-03-06 12:54:15,419: INFO: main:>>>>> stage Training started <<<<<<<]
[2024-03-06 12:54:15,427: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 12:54:15,433: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 12:54:15,435: INFO: common:created directory at: artifacts]
[2024-03-06 12:54:15,436: INFO: common:created directory at: artifacts\training]
[2024-03-06 12:56:23,226: INFO: main:>>>>>> stage Training completed <<<<<<

 x=========x]
[2024-03-06 19:10:57,363: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:10:57,423: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:10:57,426: INFO: common:created directory at: artifacts]
[2024-03-06 19:11:22,566: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:11:22,568: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:11:22,570: INFO: common:created directory at: artifacts]
[2024-03-06 19:11:33,059: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:11:33,062: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:11:33,064: INFO: common:created directory at: artifacts]
[2024-03-06 19:15:26,327: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:15:26,331: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:15:26,333: INFO: common:created directory at: artifacts]
[2024-03-06 19:17:19,408: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:17:19,411: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:17:19,430: INFO: common:created directory at: artifacts]
[2024-03-06 19:22:27,760: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:22:27,763: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:22:27,764: INFO: common:created directory at: artifacts]
[2024-03-06 19:30:56,239: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:30:56,243: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:30:56,244: INFO: common:created directory at: artifacts]
[2024-03-06 19:31:04,995: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:31:04,998: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:31:04,998: INFO: common:created directory at: artifacts]
[2024-03-06 19:31:59,446: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:31:59,449: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:31:59,450: INFO: common:created directory at: artifacts]
[2024-03-06 19:56:10,876: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:56:10,878: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:56:10,879: INFO: common:created directory at: artifacts]
[2024-03-06 19:57:31,142: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 19:57:31,149: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 19:57:31,151: INFO: common:created directory at: artifacts]
[2024-03-06 20:10:19,443: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 20:10:19,446: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 20:10:19,447: INFO: common:created directory at: artifacts]
[2024-03-06 20:10:56,012: INFO: common:json file saved at: scores.json]
[2024-03-06 20:12:02,073: WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-06 20:12:03,253: INFO: builder_impl:Assets written to: C:\Users\lenovo\AppData\Local\Temp\tmp14d0ozh9\model\data\model\assets]
[2024-03-06 21:17:32,354: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-06 21:17:32,357: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:17:32,359: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:17:32,360: INFO: common:created directory at: artifacts]
[2024-03-06 21:17:32,360: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-06 21:17:32,361: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 21:17:35,194: ERROR: main:Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?export=download&id=1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 54, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\main.py", line 17, in <module>
    data_ingestion.main()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 19, in main
    data_ingestion.download_file()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix+file_id, zip_download_dir)
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 264, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?export=download&id=1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1

but Gdown can't. Please check connections and permissions.
[2024-03-06 21:19:36,060: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-06 21:19:36,062: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:19:36,064: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:19:36,064: INFO: common:created directory at: artifacts]
[2024-03-06 21:19:36,065: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-06 21:19:36,065: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 21:19:45,192: ERROR: main:Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?export=download&id=1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 54, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\main.py", line 17, in <module>
    data_ingestion.main()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 19, in main
    data_ingestion.download_file()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix+file_id, zip_download_dir)
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 264, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?export=download&id=1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1

but Gdown can't. Please check connections and permissions.
[2024-03-06 21:25:31,930: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-06 21:25:31,932: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:25:31,933: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:25:31,934: INFO: common:created directory at: artifacts]
[2024-03-06 21:25:31,934: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-06 21:25:31,935: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 21:25:34,917: ERROR: main:Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?export=download&id=1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 54, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\main.py", line 17, in <module>
    data_ingestion.main()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 19, in main
    data_ingestion.download_file()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix+file_id, zip_download_dir)
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 264, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?export=download&id=1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1

but Gdown can't. Please check connections and permissions.
[2024-03-06 21:37:36,023: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-06 21:37:36,025: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:37:36,027: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:37:36,028: INFO: common:created directory at: artifacts]
[2024-03-06 21:37:36,029: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-06 21:37:36,029: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 21:37:38,347: ERROR: main:Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?export=download&id=1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 54, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\main.py", line 17, in <module>
    data_ingestion.main()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 19, in main
    data_ingestion.download_file()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix+file_id, zip_download_dir)
  File "d:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\site-packages\gdown\download.py", line 264, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?export=download&id=1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1

but Gdown can't. Please check connections and permissions.
[2024-03-06 21:38:32,148: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-06 21:38:32,150: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:38:32,152: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:38:32,153: INFO: common:created directory at: artifacts]
[2024-03-06 21:38:32,153: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-06 21:38:32,154: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 21:38:47,235: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 21:38:48,087: INFO: main:>>>>>> stage Data Ingestion stage completed successfully <<<<<

x=======x]
[2024-03-06 21:38:48,087: INFO: main:************]
[2024-03-06 21:38:48,088: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2024-03-06 21:38:48,089: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:38:48,091: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:38:48,091: INFO: common:created directory at: artifacts]
[2024-03-06 21:38:48,091: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-06 21:38:48,842: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-06 21:38:49,856: INFO: main:>>>>> stage Prepare base model completed <<<<<< 

 x==========x]
[2024-03-06 21:38:49,857: INFO: main:*****************]
[2024-03-06 21:38:49,858: INFO: main:>>>>> stage Training started <<<<<<<]
[2024-03-06 21:38:49,862: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:38:49,866: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:38:49,868: INFO: common:created directory at: artifacts]
[2024-03-06 21:38:49,869: INFO: common:created directory at: artifacts\training]
[2024-03-06 21:40:59,997: INFO: main:>>>>>> stage Training completed <<<<<<

 x=========x]
[2024-03-06 21:40:59,998: INFO: main:*********************]
[2024-03-06 21:40:59,998: INFO: main:>>>>>>>> stage Evaluation stage started <<<<<<<<]
[2024-03-06 21:41:00,007: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:41:00,011: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:41:00,014: INFO: common:created directory at: artifacts]
[2024-03-06 21:41:38,656: ERROR: main:name 'save_json' is not defined]
Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\main.py", line 55, in <module>
    model_evaluation.main()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 15, in main
    evaluation.evaluation()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 43, in evaluation
    self.save_score()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 47, in save_score
    save_json(path=Path("scores.json"), data=scores)
    ^^^^^^^^^
NameError: name 'save_json' is not defined
[2024-03-06 21:43:14,630: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-06 21:43:14,633: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:43:14,635: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:43:14,636: INFO: common:created directory at: artifacts]
[2024-03-06 21:43:14,637: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-06 21:43:14,637: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 21:43:31,904: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-06 21:43:32,538: INFO: main:>>>>>> stage Data Ingestion stage completed successfully <<<<<

x=======x]
[2024-03-06 21:43:32,538: INFO: main:************]
[2024-03-06 21:43:32,538: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2024-03-06 21:43:32,541: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:43:32,542: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:43:32,543: INFO: common:created directory at: artifacts]
[2024-03-06 21:43:32,543: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-06 21:43:33,113: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-06 21:43:35,267: INFO: main:>>>>> stage Prepare base model completed <<<<<< 

 x==========x]
[2024-03-06 21:43:35,268: INFO: main:*****************]
[2024-03-06 21:43:35,269: INFO: main:>>>>> stage Training started <<<<<<<]
[2024-03-06 21:43:35,274: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:43:35,279: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:43:35,280: INFO: common:created directory at: artifacts]
[2024-03-06 21:43:35,281: INFO: common:created directory at: artifacts\training]
[2024-03-06 21:45:38,390: INFO: main:>>>>>> stage Training completed <<<<<<

 x=========x]
[2024-03-06 21:45:38,391: INFO: main:*********************]
[2024-03-06 21:45:38,392: INFO: main:>>>>>>>> stage Evaluation stage started <<<<<<<<]
[2024-03-06 21:45:38,395: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-06 21:45:38,399: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-06 21:45:38,400: INFO: common:created directory at: artifacts]
[2024-03-06 21:46:17,295: INFO: common:json file saved at: scores.json]
[2024-03-06 21:46:17,296: INFO: common:json file saved at: scores.json]
[2024-03-06 21:46:19,464: WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-06 21:46:20,591: INFO: builder_impl:Assets written to: C:\Users\lenovo\AppData\Local\Temp\tmpvtlipl3m\model\data\model\assets]
[2024-03-06 21:46:36,030: INFO: dir_util:creating D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\mlruns\0\159a43c03fb54884b9b984c2041ae5f2\artifacts\model\data]
[2024-03-06 21:46:36,032: INFO: dir_util:creating D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\mlruns\0\159a43c03fb54884b9b984c2041ae5f2\artifacts\model\data\model]
[2024-03-06 21:46:36,035: INFO: dir_util:creating D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\mlruns\0\159a43c03fb54884b9b984c2041ae5f2\artifacts\model\data\model\assets]
[2024-03-06 21:46:36,040: INFO: dir_util:creating D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\mlruns\0\159a43c03fb54884b9b984c2041ae5f2\artifacts\model\data\model\variables]
[2024-03-06 21:46:36,125: INFO: main:>>>>>>>> Evaluation stage  completed successfully! <<<<<<<<<

x============x]
[2024-03-07 11:14:18,318: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 11:14:18,344: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-07 11:14:18,351: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-07 11:14:18,351: INFO: common:created directory at: artifacts]
[2024-03-07 11:14:18,464: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-07 11:14:18,465: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-07 12:05:31,223: INFO: stage_01_data_ingestion:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 12:05:31,226: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:05:31,227: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-07 12:05:31,228: INFO: common:created directory at: artifacts]
[2024-03-07 12:05:31,228: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-07 12:05:31,229: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-07 12:10:00,259: INFO: stage_01_data_ingestion:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 12:10:00,261: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:10:00,263: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-07 12:10:00,263: INFO: common:created directory at: artifacts]
[2024-03-07 12:10:00,264: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-07 12:10:00,265: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-07 12:10:03,955: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-07 12:10:03,956: ERROR: stage_01_data_ingestion:[Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 27, in <module>
    obj.main()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 20, in main
    data_ingestion.extract_zip_file()
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\components\data_ingestion.py", line 42, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\kidneyenv\Lib\zipfile.py", line 1286, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-03-07 12:14:18,382: INFO: stage_01_data_ingestion:>>>>>> stage Data Ingestion stage started <<<<<]
[2024-03-07 12:14:18,383: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:14:18,385: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-07 12:14:18,386: INFO: common:created directory at: artifacts]
[2024-03-07 12:14:18,386: INFO: common:created directory at: artifacts/data_ingestion]
[2024-03-07 12:14:18,386: INFO: data_ingestion:Downloading data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-07 12:14:32,673: INFO: data_ingestion:Downloaded data from https://drive.google.com/file/d/1tsyRtl3joEDI0wxU45PfeHb4_t-XRRK1/view?usp=share_link into file artifacts/data_ingestion/data.zip]
[2024-03-07 12:14:33,783: INFO: stage_01_data_ingestion:>>>>>> stage Data Ingestion stage completed successfully <<<<<

x=======x]
[2024-03-07 12:55:33,485: INFO: stage_02_prepare_base_model:************]
[2024-03-07 12:55:33,503: INFO: stage_02_prepare_base_model:>>>>>> stage Prepare base model started <<<<<<]
[2024-03-07 12:55:33,506: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:55:33,509: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-07 12:55:33,509: INFO: common:created directory at: artifacts]
[2024-03-07 12:55:33,510: INFO: common:created directory at: artifacts/prepare_base_model]
[2024-03-07 12:55:37,059: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-07 12:55:38,146: INFO: stage_02_prepare_base_model:>>>>> stage Prepare base model completed <<<<<< 

 x==========x]
[2024-03-07 12:55:45,750: INFO: stage_03_model_training:*****************]
[2024-03-07 12:55:45,750: INFO: stage_03_model_training:>>>>> stage Training started <<<<<<<]
[2024-03-07 12:55:45,753: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:55:45,753: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-07 12:55:45,754: INFO: common:created directory at: artifacts]
[2024-03-07 12:55:45,754: INFO: common:created directory at: artifacts\training]
[2024-03-07 12:57:53,156: INFO: stage_03_model_training:>>>>>> stage Training completed <<<<<<

 x=========x]
[2024-03-07 12:58:04,727: INFO: stage_04_model_evaluation:*********************]
[2024-03-07 12:58:04,727: INFO: stage_04_model_evaluation:>>>>>>>> stage Evaluation stage started <<<<<<<<]
[2024-03-07 12:58:04,728: ERROR: stage_04_model_evaluation:name 'obj' is not defined]
Traceback (most recent call last):
  File "D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 24, in <module>
    obj.main()
    ^^^
NameError: name 'obj' is not defined
[2024-03-07 13:05:16,596: INFO: stage_04_model_evaluation:*********************]
[2024-03-07 13:05:16,596: INFO: stage_04_model_evaluation:>>>>>>>> stage Evaluation stage started <<<<<<<<]
[2024-03-07 13:05:16,599: INFO: common:yaml file: config\config.yaml loaded successfully]
[2024-03-07 13:05:16,600: INFO: common:yaml file: params.yaml loaded successfully]
[2024-03-07 13:05:16,601: INFO: common:created directory at: artifacts]
[2024-03-07 13:05:50,660: INFO: common:json file saved at: scores.json]
[2024-03-07 13:05:50,662: INFO: common:json file saved at: scores.json]
[2024-03-07 13:05:52,837: WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-07 13:05:53,894: INFO: builder_impl:Assets written to: C:\Users\lenovo\AppData\Local\Temp\tmph_zax69s\model\data\model\assets]
[2024-03-07 13:06:17,774: INFO: dir_util:creating D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\mlruns\0\20bf1c64e23447868c8ea5a5d23b9571\artifacts\model\data]
[2024-03-07 13:06:17,779: INFO: dir_util:creating D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\mlruns\0\20bf1c64e23447868c8ea5a5d23b9571\artifacts\model\data\model]
[2024-03-07 13:06:17,781: INFO: dir_util:creating D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\mlruns\0\20bf1c64e23447868c8ea5a5d23b9571\artifacts\model\data\model\assets]
[2024-03-07 13:06:17,786: INFO: dir_util:creating D:\MLOPs Project\Kidney_Disease_Classification_Ml_Dvc\mlruns\0\20bf1c64e23447868c8ea5a5d23b9571\artifacts\model\data\model\variables]
[2024-03-07 13:06:17,921: INFO: stage_04_model_evaluation:>>>>>>>> Evaluation stage  completed successfully! <<<<<<<<<

x============x]
